// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polar_align.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package polar_align;

