// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polar_align.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package polar_align;

@kotlin.jvm.JvmName("-initializepolarError")
public inline fun polarError(block: polar_align.PolarErrorKt.Dsl.() -> kotlin.Unit): polar_align.PolarAlign.PolarError =
  polar_align.PolarErrorKt.Dsl._create(polar_align.PolarAlign.PolarError.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `polar_align.PolarError`
 */
public object PolarErrorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: polar_align.PolarAlign.PolarError.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: polar_align.PolarAlign.PolarError.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): polar_align.PolarAlign.PolarError = _builder.build()

    /**
     * `float ra = 1;`
     */
    public var ra: kotlin.Float
      @JvmName("getRa")
      get() = _builder.getRa()
      @JvmName("setRa")
      set(value) {
        _builder.setRa(value)
      }
    /**
     * `float ra = 1;`
     */
    public fun clearRa() {
      _builder.clearRa()
    }

    /**
     * `float dec = 2;`
     */
    public var dec: kotlin.Float
      @JvmName("getDec")
      get() = _builder.getDec()
      @JvmName("setDec")
      set(value) {
        _builder.setDec(value)
      }
    /**
     * `float dec = 2;`
     */
    public fun clearDec() {
      _builder.clearDec()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun polar_align.PolarAlign.PolarError.copy(block: `polar_align`.PolarErrorKt.Dsl.() -> kotlin.Unit): polar_align.PolarAlign.PolarError =
  `polar_align`.PolarErrorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

