// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polar_align.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package polar_align;

@kotlin.jvm.JvmName("-initializeresponse")
public inline fun response(block: polar_align.ResponseKt.Dsl.() -> kotlin.Unit): polar_align.PolarAlign.Response =
  polar_align.ResponseKt.Dsl._create(polar_align.PolarAlign.Response.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `polar_align.Response`
 */
public object ResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: polar_align.PolarAlign.Response.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: polar_align.PolarAlign.Response.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): polar_align.PolarAlign.Response = _builder.build()

    /**
     * `bool stopped = 1;`
     */
    public var stopped: kotlin.Boolean
      @JvmName("getStopped")
      get() = _builder.getStopped()
      @JvmName("setStopped")
      set(value) {
        _builder.setStopped(value)
      }
    /**
     * `bool stopped = 1;`
     */
    public fun clearStopped() {
      _builder.clearStopped()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun polar_align.PolarAlign.Response.copy(block: `polar_align`.ResponseKt.Dsl.() -> kotlin.Unit): polar_align.PolarAlign.Response =
  `polar_align`.ResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

